services:
  - type: web
    name: gouri-project-web
    runtime: docker
    dockerfilePath: ./Dockerfile
    autoDeployTrigger: commit
    healthCheckPath: /
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: LOG_CHANNEL
        value: stderr
      - key: APP_KEY
        sync: false
      - key: APP_URL
        sync: false
      - key: ASSET_URL
        sync: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_URL
        sync: false
