# AI Web Builder — Whitepaper & Product Requirements Document (WP.PRD)

**Document Version:** 1.0.0  
**Project Codename:** Universal AI Web Builder (AWB)  
**Classification:** Technical Whitepaper & Product Requirements Specification  
**Authors:** AI Web Builder Architecture & Engineering Team  
**Date:** September 2026  
**License:** MIT License  

---

## 1. Executive Summary & Vision

### 1.1 Executive Summary
**AI Web Builder (AWB)** is a local-first, open-source, universal website generation platform. It synthesizes architectural patterns from over 46 generative AI website builder experiments into a single cohesive platform. 

Unlike conventional AI code generation tools that emit unstyled snippets or shallow single-file demonstrations, AWB creates **production-grade, 13-layer full-stack software architectures** directly from natural language prompts, starter templates, or live website clones.

### 1.2 Core Pillars
1. **Local-First & Sovereign AI**: Operates 100% offline using local inference runtimes (Ollama, llama.cpp, ComfyUI) with zero telemetry, zero mandatory cloud accounts, and zero subscription lock-in.
2. **13-Layer Architecture**: Generates not merely frontends, but comprehensive systems encompassing UI, API, Database, Authentication, Storage, CI/CD, Deployment, Testing, Security, Rate Limiting, Caching, Load Balancing, and Observability/Recovery.
3. **Dual Delivery Modality**: Distributed both as a lightweight client-side Next.js web application and as a native desktop application (Windows NSIS EXE, macOS DMG, Linux AppImage) powered by Electron.
4. **Provider-Agnostic Engine**: Unified runtime abstraction over 10+ AI providers (local Ollama/llama.cpp and cloud OpenAI, Anthropic, Google Gemini, Groq, DeepSeek, Mistral, Together AI, and OpenRouter).
5. **Structural Website Cloning**: Employs an intelligent BFS web crawler to extract architectural layout and typography context from live sites without scraping copyrighted assets.

---

## 2. Product Requirements & Feature Specifications

### 2.1 User Personas & Use Cases
| Persona | Goals | Key Pain Points Solved |
| :--- | :--- | :--- |
| **Independent Developers** | Bootstrap full-stack applications in minutes with robust CI/CD and DB layers | Replaces repetitive boilerplate configuration; eliminates manual Docker/Auth/DB wiring |
| **Freelancers & Agencies** | Rapidly prototype and deliver custom websites tailored to client references | Clone-to-code pipeline turns live competitor sites into customizable architecture |
| **Enterprise & Privacy Teams** | Generate internal tooling and portals in air-gapped environments | 100% offline local inference with Ollama ensures zero data leaves local infrastructure |
| **Non-Technical Founders** | Translate business concepts into working software prototypes | Plain-English conversational generation with one-click preview and export |

---

## 3. System Architecture & Monorepo Topology

AWB is orchestrated using **Turborepo** with **pnpm workspaces** for sub-second builds, strict module boundaries, and shared code reuse.

```
ai-web-builder/
├── apps/
│   ├── web/                          # Next.js 15 App Router Browser Experience
│   │   ├── src/
│   │   │   ├── app/                  # Route layouts, globals, page controllers
│   │   │   └── components/           # UI views: Builder, Layers, Clone, Preview, Settings
│   │   └── package.json
│   └── desktop/                      # Electron 34 Native Desktop Shell
│       ├── electron/                 # IPC main process, security preload bridge, menus
│       └── package.json
├── packages/
│   ├── core/                         # Core Business Logic & Orchestration Engine
│   │   ├── src/providers/            # 10+ AI provider drivers & connection testing
│   │   ├── src/generator/            # Prompt builder, file parser, layer applier
│   │   ├── src/layers/               # 13-layer definitions, options schema & code injectors
│   │   ├── src/clone/                # BFS crawler, DOM parser, context synthesizer
│   │   ├── src/assets/               # SVG generators, Pexels, Unsplash, ComfyUI drivers
│   │   ├── src/settings/             # Zod validation schema & default configurations
│   │   └── src/templates/            # 10 curated starter blueprints
│   ├── ui/                           # Shared design system components (Tailwind CSS 4)
│   └── config/                       # Central application constants, ports, engine settings
├── unraid/                           # Community Applications XML templates
├── docker-compose.yml                # Production multi-container bundle (Web + Ollama)
├── docker-compose.dev.yml            # Development hot-reload configuration
└── pnpm-workspace.yaml               # Monorepo workspace configuration
```

---

## 4. The 13 Production Layers Architecture

Every website generated by AWB incorporates a layered architectural stack. Each layer is independently toggleable and configurable prior to generation:

```
┌─────────────────────────────────────────────────────────────┐
│  Layer 1: Presentation & UI (Next.js / React / Tailwind)    │
├─────────────────────────────────────────────────────────────┤
│  Layer 2: API & Routing (Route Handlers, TRPC, REST)        │
├─────────────────────────────────────────────────────────────┤
│  Layer 3: Database & ORM (Prisma, PostgreSQL, SQLite)       │
├─────────────────────────────────────────────────────────────┤
│  Layer 4: Authentication & Authorization (NextAuth, JWT)    │
├─────────────────────────────────────────────────────────────┤
│  Layer 5: Storage & Media (S3, Cloudinary, Local FS)        │
├─────────────────────────────────────────────────────────────┤
│  Layer 6: CI/CD Pipelines (GitHub Actions, GitLab CI)       │
├─────────────────────────────────────────────────────────────┤
│  Layer 7: Deployment & Infrastructure (Dockerfile, Vercel)  │
├─────────────────────────────────────────────────────────────┤
│  Layer 8: Testing & Quality (Vitest, Playwright, RTL)       │
├─────────────────────────────────────────────────────────────┤
│  Layer 9: Security & Hardening (Helmet, CSP, CORS, Sanitize)│
├─────────────────────────────────────────────────────────────┤
│  Layer 10: Rate Limiting & Abuse Prevention (Upstash/Redis) │
├─────────────────────────────────────────────────────────────┤
│  Layer 11: Caching & Performance (Redis, SWR, Edge Cache)   │
├─────────────────────────────────────────────────────────────┤
│  Layer 12: Load Balancing & Reverse Proxy (NGINX, Caddy)    │
├─────────────────────────────────────────────────────────────┤
│  Layer 13: Observability, Error Tracking & Recovery (Sentry)│
└─────────────────────────────────────────────────────────────┘
```

### Layer Detail Specifications
1. **Layer 1: Presentation & UI**: Generates semantic HTML5, accessible React/TSX components, responsive design tokens with Tailwind CSS v4, dynamic color themes, and fluid typography.
2. **Layer 2: API & Routing**: Generates Next.js App Router Route Handlers (`src/app/api/.../route.ts`) with request validation via Zod, error handling, and structured JSON responses.
3. **Layer 3: Database & ORM**: Emits Prisma schema files (`schema.prisma`), database migration scripts, connection pooling logic, and typed seed files. Supports PostgreSQL, MySQL, SQLite, and MongoDB.
4. **Layer 4: Authentication**: Implements NextAuth / Auth.js v5 or lightweight JWT session handlers with middleware protection, OAuth provider stubs, and credential encryption (bcrypt).
5. **Layer 5: Storage & Media**: Provides file upload handlers, presigned S3/R2 URL generators, and fallback local filesystem storage drivers with MIME-type sanitization.
6. **Layer 6: CI/CD Pipeline**: Generates automated `.github/workflows/ci.yml` configurations with automated linting, type-checking, test runs, and preview builds.
7. **Layer 7: Deployment**: Generates multi-stage production Dockerfiles, `docker-compose.yml`, and `vercel.json` deployment manifests.
8. **Layer 8: Testing**: Emits unit test suites (`*.test.ts`) using Vitest, integration tests for API endpoints, and end-to-end test scaffolds with Playwright.
9. **Layer 9: Security**: Injects Content Security Policy (CSP), HTTP security headers, CORS origin allowlists, input sanitization helpers, and SQL/XSS prevention guards.
10. **Layer 10: Rate Limiting**: Implements token-bucket or sliding-window rate limiters utilizing in-memory counters or Redis/Upstash for public endpoints.
11. **Layer 11: Caching**: Configures HTTP cache-control headers, stale-while-revalidate policies, and Redis cache invalidation keys.
12. **Layer 12: Reverse Proxy & Load Balancing**: Generates NGINX or Caddy reverse proxy configurations with automatic HTTPS and gzip/brotli compression.
13. **Layer 13: Observability & Recovery**: Emits structured logging utilities, Sentry/OpenTelemetry tracing hooks, health check endpoints (`/api/health`), and global error boundaries (`error.tsx`).

---

## 5. Multi-Provider AI Inference Engine

AWB features a unified driver abstraction (`Provider` interface) permitting seamless runtime switching across 10+ AI backends without altering prompt structure:

| Provider | Type | Default Model | Connectivity / Protocol | Offline Capable |
| :--- | :--- | :--- | :--- | :--- |
| **Ollama** | Local | `llama3.1:8b` / `qwen2.5-coder` | HTTP REST (`http://localhost:11434`) | Yes (100%) |
| **llama.cpp** | Local | `default` | HTTP REST (`http://localhost:8080`) | Yes (100%) |
| **ComfyUI** | Local | `sd_xl_base_1.0` | WebSocket / REST (`http://127.0.0.1:8188`) | Yes (100%) |
| **OpenAI** | Cloud | `gpt-4o` | HTTPS REST (Bearer Token) | No |
| **Anthropic** | Cloud | `claude-3-5-sonnet` | HTTPS REST (`x-api-key`) | No |
| **Google Gemini** | Cloud | `gemini-1.5-pro` | HTTPS REST (`x-goog-api-key`) | No |
| **Groq** | Cloud | `llama-3.3-70b-versatile` | Ultra-fast LPU HTTPS REST | No |
| **DeepSeek** | Cloud | `deepseek-coder` | HTTPS REST | No |
| **Mistral AI** | Cloud | `codestral-latest` | HTTPS REST | No |
| **Together AI** | Cloud | `meta-llama/Llama-3-70b` | HTTPS REST | No |
| **OpenRouter** | Cloud | `auto` | Unified multi-model gateway | No |

### Dynamic Model Resolution
The provider registry automatically detects active local models via `/api/tags` (for Ollama) and gracefully falls back to installed models rather than failing when arbitrary hardcoded defaults are absent.

---

## 6. Structural Website Cloning Engine

AWB includes an intelligent, non-invasive website cloner (`@awb/core/clone`):
- **Crawl Strategy**: Breadth-First Search (BFS) crawler navigating internal domain links up to configurable depth (0 to 3) and page caps (1 to 20).
- **DOM & Style Extraction**: Extracts semantic document hierarchy (header, nav, main, sections, footer), forms, color palettes, and typography tokens using `node-html-parser`.
- **Architectural Synthesis**: Synthesizes the extracted patterns into a clean prompt context (`buildPromptContext()`), providing the AI model with layout inspiration without copying third-party code or proprietary assets.

---

## 7. Multi-Source Asset & Image Generation Engine

To ensure generated sites are visually complete immediately upon export:
1. **Zero-Dependency SVG Engines**: 8 programmatic vector pattern generators (gradient, dots, geometric, waves, grid, crosshatch, abstract, hero).
2. **Stock Photography APIs**: Integrated Pexels and Unsplash search clients with automatic fallback to modern Unsplash Source URLs.
3. **Local Generative Images**: ComfyUI SDXL/SD1.5 pipeline for generating high-resolution custom imagery completely offline.
4. **Cloud Generative Images**: OpenAI DALL-E 3 image generation driver.

---

## 8. Desktop App Architecture (Electron 34)

- **Main Process (`electron/main.js`)**: Spawns isolated Chromium instances, manages native OS menus, handles cross-platform window state, and registers IPC handlers.
- **Preload Bridge (`electron/preload.js`)**: Implements strict `contextIsolation: true` and `nodeIntegration: false`, exposing typed APIs through `contextBridge.exposeInMainWorld('awb', ...)`.
- **Packaging & Targets**: Packaged using `electron-builder` producing:
  - Windows: 64-bit NSIS executable installer (~143 MB).
  - macOS: Universal DMG supporting Apple Silicon and Intel.
  - Linux: AppImage, Snap, and `.deb` bundles.

---

## 9. Deployment Topologies

1. **Bare-Metal / Developer Machine**:
   - `pnpm install` -> `pnpm web` (Browser at `http://localhost:3000`)
   - `pnpm desktop` (Native Electron application)
2. **Docker Compose Production Stack**:
   - Containerized Next.js frontend with an isolated Ollama sidecar container with NVIDIA GPU passthrough support.
3. **Unraid Community Applications**:
   - Packaged XML template with 20+ configurable environment variables, volume mappings for persistent model caches (`/root/.ollama`), and WebUI bindings.

---

## 10. Security, Privacy & Sovereign Computing Guarantees

- **Zero Telemetry**: No tracking beacons, analytics scripts, or phone-home requests.
- **Local Storage Security**: Cloud API keys and provider tokens are retained exclusively in the client's local storage or encrypted OS keychain; keys are never transmitted to any third-party intermediary.
- **Safe Sandboxing**: Generated code preview renders inside sandboxed `<iframe>` instances with restricted capabilities (`sandbox="allow-scripts"` without allowing top-level navigation).

---

## 11. Technical Specifications & Data Models

### 11.1 Site Configuration Model (`SiteConfig`)
```typescript
interface SiteConfig {
  name: string
  description: string
  type: 'landing-page' | 'saas' | 'ecommerce' | 'portfolio' | 'blog' | 'docs' | 'agency' | 'dashboard' | 'mobile-first' | 'minimal'
  framework: 'nextjs' | 'react' | 'astro' | 'static'
  styling: 'tailwind' | 'css-modules' | 'styled' | 'vanilla'
  pages: string[]
  features: string[]
  colorScheme: 'indigo' | 'blue' | 'emerald' | 'amber' | 'rose' | 'violet' | 'slate' | 'cyan'
  typography: 'inter' | 'plus-jakarta-sans' | 'literata' | 'satoshi'
  language: 'typescript' | 'javascript'
  locale: string
  seo: boolean
  analytics: boolean
  forms: boolean
  blog: boolean
  darkMode: boolean
  multilingual: boolean
}
```

### 11.2 Generated File Structure (`GeneratedFile`)
```typescript
interface GeneratedFile {
  path: string
  content: string
  language: string
}
```

### 11.3 Generation Response Envelope (`GenerationResult`)
```typescript
interface GenerationResult {
  id: string
  siteConfig: SiteConfig
  layers: LayerConfig[]
  files: GeneratedFile[]
  stdout: string
  model: string
  provider: string
  duration: number
  tokenUsage?: {
    promptTokens?: number
    completionTokens?: number
    totalTokens?: number
  }
}
```

---

## 12. Product Roadmap & Future Milestones

- **v0.3.0**: Real-time token streaming with live side-by-side component diffing.
- **v0.4.0**: Interactive visual drag-and-drop canvas overlay on top of generated React components.
- **v0.5.0**: One-click direct deployment integrations to Vercel, Netlify, Cloudflare Pages, and GitHub Pages.
- **v1.0.0 (GA)**: Multi-agent generation pipeline (Design Agent, Architecture Agent, QA/Testing Agent, Security Auditor) running concurrently on local LLMs.
